# Generated by Django 2.2 on 2021-07-21 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0003_experiencemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencemodel',
            name='timespan',
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='from_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencemodel',
            name='to_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='type',
            field=models.CharField(choices=[('E', 'Education'), ('W', 'Work')], max_length=1),
        ),
    ]
