# Generated by Django 2.2 on 2021-07-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0005_auto_20210725_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='short_description',
            new_name='position',
        ),
    ]
