# Generated by Django 2.2 on 2021-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0007_applicationmodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='interview_link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
