# Generated by Django 2.2 on 2021-08-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0009_remove_testmodel_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscoremodel',
            name='score',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
