# Generated by Django 2.2 on 2021-08-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0011_auto_20210803_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testscoremodel',
            name='user',
        ),
    ]
