# Generated by Django 2.2 on 2021-08-02 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruiter', '0008_applicationmodel_interview_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='duration',
        ),
    ]
